# Generated by Django 6.0.2 on 2026-03-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('IND', 'India (₹)'), ('USA', 'United States ($)'), ('UK', 'United Kingdom (£)'), ('EUR', 'Europe (€)')], default='IND', max_length=3),
        ),
    ]
