# Generated by Django 6.0.2 on 2026-03-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_apartment_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_provider',
            field=models.CharField(blank=True, choices=[('Blue Dart', 'Blue Dart'), ('Delhivery', 'Delhivery'), ('DTDC', 'DTDC'), ('Ecom Express', 'Ecom Express'), ('Amazon Shipping', 'Amazon Shipping'), ('Xpressbees', 'Xpressbees'), ('India Post', 'India Post'), ('Other', 'Other')], help_text='Select the courier service', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Enter the AWB/Tracking number', max_length=100, null=True),
        ),
    ]
