# Generated by Django 6.0.2 on 2026-03-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_provider_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Online Payment (Razorpay)'), ('UPI', 'UPI ID'), ('COD', 'Cash on Delivery (COD)')], default='RAZORPAY', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Enter your UPI ID if paying via UPI', max_length=100, null=True),
        ),
    ]
